### ISSUE TITLE
First release tracking issue

### ISSUE THREAD

**Issue by RDambrosio016** [RDambrosio016/Rust-CUDA#2]
Small issue to track the things that need to be done before the project will be released.

- [x] Get CGUs to work, needs work on the codegen to merge llvm ir modules, probably not too hard.
- [ ] ~~Add a couple more basic examples.~~
- [ ] ~~Update nightly close to release.~~
- [ ] ~~Merge #1~~ 
- [x] Make i128 work, shouldn't be too hard, just removing special casing for it since we already handle irregular ints just fine.
- [ ] ~~[meta] Add proper labels and maybe templates~~
- [x] Add the raytracer i posted to the examples
- [x] Actually pass codegen args in cuda_builder
- [ ] ~~Make the readme~~
- [x] implement the ABI calculation logic, probably the hardest thing here
- [x] Use prebuilt LLVM.
